In [ ]:
import torch
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

Creating Sensors

In [ ]:
#Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()#Get tensor back as python int

7

In [ ]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

# Matrix

In [ ]:
matrix=torch.tensor([[7,8],
                     [9,10]
                     ])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0],matrix[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [ ]:
type(matrix)

torch.Tensor

In [ ]:
#Tensor
Tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]
                      ]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

In [ ]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors

In [ ]:
#random tensor of shape (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9640, 0.6101, 0.7645, 0.7108],
        [0.1087, 0.3027, 0.7032, 0.1212],
        [0.3163, 0.5461, 0.9212, 0.7298]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_tensor=torch.rand(size=(224,224,3))
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Creating range of Tensors and Tensors like

In [ ]:
# Use torch.range
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [ ]:
#flot 32 tensors

flot_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,
                            device=None,
                            requires_grad=False
                            )
flot_32_tensor

tensor([3., 6., 9.])

In [ ]:
flot_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=flot_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*flot_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([23,33,44],dtype=torch.int32)
int_32_tensor

tensor([23, 33, 44], dtype=torch.int32)

In [ ]:
int_32_tensor*flot_32_tensor

tensor([ 69., 198., 396.])

In [ ]:
int_32_tensor.device

device(type='cpu')

In [ ]:
int_32_tensor.dtype

torch.int32

In [ ]:
int_32_tensor.shape

torch.Size([3])

## Manipulating Tensors

In [ ]:
tensor=torch.tensor([1,2,3]) #adding
tensor+10

tensor([11, 12, 13])

In [ ]:
#multiply
tensor*10

tensor([10, 20, 30])

In [ ]:
#subtract
tensor-10

tensor([-9, -8, -7])

In [ ]:
#Inbuilt func
torch.mul(tensor,10)

tensor([10, 20, 30])

## Matrix Multiplication

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor*tensor

tensor([1, 4, 9])

In [ ]:
#Element wise multiplication
tensor*tensor

tensor([1, 4, 9])

In [ ]:
#Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
# Shape for matrix multiplication
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]
                       ])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]
                       ])

torch.mm(tensor_A,tensor_B) #same as matmul

RuntimeError: ignored

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Tensor Aggregation

In [ ]:
#Create tensor
x=torch.arange(0,100,10,dtype=torch.float16)
x,x.dtype

(tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16),
 torch.float16)

In [ ]:
#Find min
torch.min(x),x.min()

(tensor(0., dtype=torch.float16), tensor(0., dtype=torch.float16))

In [ ]:
#max
torch.max(x),x.min()

(tensor(90., dtype=torch.float16), tensor(0., dtype=torch.float16))

In [ ]:
#find mean
torch.mean(x)

tensor(45., dtype=torch.float16)

In [ ]:
#Sum
x.sum()

tensor(450., dtype=torch.float16)

## Finding positional min and max

In [ ]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
x.argmin()#index at which lowest element is there

tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Reshaping,stacking,squeezing and unsqueezing tensors

In [ ]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
 #Add extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x coz they share same memory
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
#torch.squueze
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze(),x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_squeezed=x_reshaped.squeeze()
x_squeezed,x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_unsqueezed=x_squeezed.unsqueeze(dim=0)

In [ ]:
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
## torch.permute method -rearrange dim in specified order
x_original=torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [ ]:
#Permute the original tensor to rearrange the axis (or dim) order
x_permute=x_original.permute(2,0,1)
x_permute.shape

torch.Size([3, 224, 224])

## Indexing (selecting data from tensors)

In [ ]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#index on tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][2]

tensor(3)

In [ ]:
x[0][2][2]

tensor(9)

## Pytorch and Numpy

In [ ]:
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor.dtype

torch.float32

In [ ]:
#Tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproduciblity

In [ ]:
import torch

#creat 2 random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
random_tensor_A,random_tensor_B

(tensor([[0.1269, 0.6764, 0.5261, 0.8941],
         [0.2071, 0.3140, 0.0918, 0.9923],
         [0.6275, 0.2749, 0.1698, 0.0832]]),
 tensor([[0.3150, 0.0321, 0.6280, 0.3059],
         [0.5939, 0.8561, 0.3800, 0.3270],
         [0.3550, 0.6800, 0.2676, 0.8720]]))

In [1]:
# Making reproducible tensors
import torch

#Set random seed
random_seed=42
torch.manual_seed(random_seed)
random_tensor_c=torch.rand(3,4)
random_tensor_d=torch.rand(3,4)
random_tensor_c,random_tensor_d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]))

In [2]:
#Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## Putting Tensor on GPU

In [3]:
#Create a tensor(default on cpu )
import torch
tensor=torch.tensor([1,2,3])
#tensor not on gpu
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [4]:
#Move tensor to gpu
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [5]:
#if tensor is on gpu,cant transform it to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [6]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])